### ISSUE TITLE
Some questions about replica method

### ISSUE THREAD

**Issue by tttttcx** [benjaminaubin/Tutorial_AMP_Replicas#1]
Dear @benjaminaubin 
  Thank you for your sharing,this Tutorial help me a lot! About  Page26 in Tutorial, how can you get the result  of q = 2*d(_I_w)/d(q_hat) and q_hat = 2*alpha*d(_I_z)/d(q), which is absolutely important in proving  the consistency between the replica method and SE in AMP algorithm. It seems that some steps have been omitted in this tutorial. I try to derive this formula  for a long time, but failed. If possible,could you give me some detailed description about this formula? Best wishes!

**Comment by benjaminaubin** [comment]
Dear @tttttcx,

You are completely right that the simplification of the fixed point equations (from the replica computation eq 40-41, bottom of page 21) is crucial to draw the connection with the AMP state evolution equation (eq 10 or eq 43). 
However, I did not find the reference you mentionned page 26: are you not refering instead to the expressions in III.F and D.2 ?

In fact, I did not add the corresponding computation in these notes because it is quite cumbersome. However, I included it in the appendix of one of my recent papers: https://arxiv.org/pdf/2006.06560.pdf (page 47-50), the notations are slightly different but you should figure it out easily. Let me know if it helped! 

Best!

**Comment by tttttcx** [comment]
Dear @benjaminaubin

Thank you so much, your recent papers really helped me solve the problem.  I just download the Tutorial from the github, and I think  it's different from the one which I got last year. But the material you have given me is indeed the answer to my question. I read your other papers the other months, you did a great job! I think my research direction is very similar to yours. If there is an opportunity, I hope to communicate with you about our research direction in the future. Best wishes!
