### ISSUE TITLE
Some derivation problems about the Tutorial notes

### ISSUE THREAD

**Issue by tttttcx** [benjaminaubin/Tutorial_AMP_Replicas#2]
Dear @benjaminaubin 

I found some derivation "errors" in your Tutorial, Maybe it's because you skipped some steps, but I cannot get it. I marked what I thought might be wrong in this file 
[Tutorial-Pages-22-25.pdf](https://github.com/benjaminaubin/Tutorial_AMP_Replicas/files/6094931/Tutorial-Pages-22-25.pdf)

If you omit some steps there, could you give some detailed description about that? Best wishes！

**Comment by benjaminaubin** [comment]
Dear @tttttcx,

Thank you for pointing out the typos. I wrote these notes a long time ago, and they contain indeed some mistakes. I will edit a new version as soon as possible with the correct derivation. Meanwhile, you can check the derivation for committee machines in the appendices of https://tel.archives-ouvertes.fr/tel-03125117. 

Best!

**Comment by tttttcx** [comment]
Dear @benjaminaubin，

Thank you for sharing,I will read this book carefully. By the way,if you  finish the new version, if possible, could you share the new version with me in github? Best wishes!

**Comment by tttttcx** [comment]
Dear @benjaminaubin

I found some derivation "errors" in your new file, Maybe it's because you skipped some steps or  I got it wrong. I marked what I thought might be wrong in this file
[Mean-field methods and algorithmic perspectives for high-dimensional machine learning-Pages-334-338.pdf](https://github.com/benjaminaubin/Tutorial_AMP_Replicas/files/6096691/Mean-field.methods.and.algorithmic.perspectives.for.high-dimensional.machine.learning-Pages-334-338.pdf)
[Mean-field methods and algorithmic perspectives for high-dimensional machine learning-Pages339-341.pdf](https://github.com/benjaminaubin/Tutorial_AMP_Replicas/files/6096769/Mean-field.methods.and.algorithmic.perspectives.for.high-dimensional.machine.learning-Pages339-341.pdf)



I hope you can correct me if I got it wrong. Best wishes！

**Comment by benjaminaubin** [comment]
Dear @tttttcx ,

Thanks for reading the materials. 

Concerning page 334-338: 
- the term labeled in red is correct up to a typo in (305): it should be Q^aa_kk' w_k^a w_k'^a
- Then term A is exactly the quadratic form in the exponential in (305) up to the mentioned typo
- Then in B I forgot the term w^* Q_hat^* w^* that appears again in the second line of 311 (and there is a typo in the shape of the Q_hat replica matrix in 309, it should be Q_hat^* instead of -1/2 Q_hat^*).  
- But the coefficients are correct: notice the convention -1/2 Q_hat in eq 309
- And C follows directly from B by adding/removing the missing terms

Concerning page 339-341: 
- To compute the expressions of the inverse and determinant (312-313): the computation is quite cumbersome and is based on the writing of the overlap matrix Q as a block matrix and each block can be written as Kronecker products. Using properties of the inverse/determinant of block matrices, basic linear algebra and a generalization of the Sherman-Morrison formula, we obtain the result. Please check the computation in an old set of notes in here: 
[inverse_determinant.pdf](https://github.com/benjaminaubin/Tutorial_AMP_Replicas/files/6108002/inverse_determinant.pdf)

- Also there was a typo: I mixed \tilde{Q} and \tilde{q} in the last two lines of 312-313.
- To shorten the computation, I indeed skipped a cumbersome computation: please find the extended computation with some of the above typos that have been corrected:
[replicas.pdf](https://github.com/benjaminaubin/Tutorial_AMP_Replicas/files/6108120/replicas.pdf)
 - There still might be typos as I do not have much time to review my notes. Please try to reproduce the steps on your own as explained and you should be able to recover the final result.
 
I hope this helps!
Best

**Comment by benjaminaubin** [comment]
Dear @tttttcx, 

I am working on a set of notes to update the old notes present in this repo and gather all the different missing derivations. Once I pushed it, please feel free to check the typos and contribute to clarify the notes  🤓.

Best!
